myapp/urls.py
from django.urls import path,include
from . import views
urlpatterns = [
    path('', views.index, name='index'),
    path('profile/', views.profile, name='profile'),
    path('register/', views.register, name='register'),
    path('gallery/', views.Gallery, name='gallery'),

# images url
    path('images/', views.ImageListView.as_view(), name='image_list'),
    path('images/upload/', views.ImageCreateView.as_view(), name='image_upload'),
    path('images/<int:pk>/delete/', views.ImageDeleteView.as_view(), name='image_delete'),
# search
    path('search/', views.search, name='search'),
# serach tag
    path("search/<str:tag>",views.search_tag,name='search_tag'),
#images view
    path('image_view/<int:pk>/',views.Imageview, name='image_view'),
    
# non login user
    path('user_profile/<int:pk>/',views.profile_view, name='profile_view'),
# SERVER UP TIME 
    path('get-uptime/', views.get_uptime_data, name='get_uptime'),



]

pexels/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from myapp import views


urlpatterns = [
    path('',include("myapp.urls")),
    # path('login', auth_views.LoginView.as_view(), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('superman', admin.site.urls, name='superman'),
    path('login', views.CustomLoginView.as_view(), name='login_page'),
    path('', include('django_prometheus.urls')),

    
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

myapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=100, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    profile_picture = models.ImageField(upload_to='profile_pics/', blank=True)

    def __str__(self):
        return self.user.username



@receiver(post_save, sender=User)
def create_or_update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()
 #aswin123456@
 
 
#  imagies model to save user give images 
class Image(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to='images/')
    description = models.TextField(blank=True, null=True)
    tags = models.CharField(max_length=255, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.description or 'Untitled'} by {self.user.username}"

myapp/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile, Image
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate


class RegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        
    def clean_email(self):
        email = self.cleaned_data.get('email')  
        print('here')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('A user with this email already exists.')
        return email


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['bio', 'location', 'birth_date', 'profile_picture']


# email change
class EmailAuthenticationForm(AuthenticationForm):
    username = forms.CharField(label='Email')

    
    def clean(self):
        email = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        print(email,password)
        
        if email and password:
        # Call the default backend for authentication
            self.user_cache = authenticate(
                request=self.request,
                username=email,  # Email will be used as the username
                password=password
            )
        
            print(self.user_cache)
            if self.user_cache is None:
                raise forms.ValidationError(
                    'invalid email',
                    code='invalid_login',
                    )
        return self.cleaned_data
    
# images upload view


class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['image', 'description', 'tags']

myapp/views.py
# Create your views here.
from django.shortcuts import render, redirect
from django.contrib.auth import login
from .forms import RegisterForm, ProfileForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from  .images_views import *
from django.contrib.auth import views as auth_views
from .forms import EmailAuthenticationForm
from .models import Image as ImageModel
from django.db.models import Q
from django.conf import settings
from django.http import JsonResponse
from datetime import datetime




def get_uptime_data(request):
    current_time = datetime.now()
    server_start_time = settings.SERVER_START_TIME
    uptime_duration = current_time - server_start_time

    uptime_seconds = uptime_duration.total_seconds()
    uptime_hours, remainder = divmod(uptime_seconds, 3600)
    uptime_minutes, uptime_seconds = divmod(remainder, 60)

    return JsonResponse({
        'uptime_hours': int(uptime_hours),
        'uptime_minutes': int(uptime_minutes),
        'uptime_seconds': int(uptime_seconds),
    })


#index page
def index(request):
    
        
    
    context={
        'images':ImageModel.objects.all().order_by('-created_at')
    }
    if request.user.is_staff:
        context.update({
            "imagecount":ImageModel.objects.count(),
            "usercount":User.objects.count()
        })
    
    return render(request, 'index.html',context)

def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        print(form.is_valid())
        if form.is_valid():
            
            user = form.save()
            print('asd')

            # login(request, user)
            login(request, user, backend='django.contrib.auth.backends.ModelBackend')

            return redirect('profile')  # Redirect to the home page after registration
        else:
            print(form.errors)
    else:
        form = RegisterForm()
    return render(request, 'registration/register.html', {'form': form})


@login_required(login_url='login_page')
def profile(request):
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if form.is_valid():
            form.save()
            return redirect('profile')
    else:
        form = ProfileForm(instance=request.user.profile)
    return render(request, 'profile.html', {'form': form})



@login_required(login_url='login_page')
def Gallery(request):
    
    context={
        'images':ImageModel.objects.filter(user=request.user).order_by('-created_at')

        
    }
    return render(request, 'gallery.html', context)



class CustomLoginView(auth_views.LoginView):
    form_class = EmailAuthenticationForm
    
    
# search

def search(request):
    query = request.GET.get('word')  # Get 'q' from GET request or use 'word' from URL
    # Filter images based on tags or description matching the word
    print(query)
    if query:
        images = ImageModel.objects.filter(Q(tags__icontains=query) | Q(description__icontains=query))
    else:
        images = ImageModel.objects.none()  # Return empty queryset if no query
    
    
    
    # Prepare the context for rendering
    context = {
        'images': images
    }
    
    return render(request, 'search.html', context)    


# images view
def Imageview(request,pk):
    image=ImageModel.objects.filter(pk=pk)
    print(image)
    context={  
        'image':image[0],
        'all':ImageModel.objects.exclude(pk=pk)
    }
    
    return render(request,'view_image.html',context)


# user profile view for non login user 
def profile_view(request,pk):
    
    context={
        "image":ImageModel.objects.filter(pk=pk)[0],
        "all":ImageModel.objects.filter(pk=pk)


    }
    return render(request,'non_login/profile.html',context)

# tag based search 
def search_tag(request,tag):
    query = tag  
    print(query)
    if query:
        images = ImageModel.objects.filter(Q(tags__icontains=query) | Q(description__icontains=query))
    else:
        images = ImageModel.objects.none()  # Return empty queryset if no query
    
    
    
    # Prepare the context for rendering
    context = {
        'images': images
    }
    
    return render(request, 'search.html', context)    

myapp/templates/gallery.html
{% extends "index.html" %}
{% block content %}
   <section class="pt-16">
       <div class="w-full  px-6 mx-auto">
           <div class="relative flex flex-col min-w-0 break-words bg-white w-full mb-6 shadow-xl rounded-lg mt-16">
               <div class="px-6  ">
                   <div class="flex flex-wrap justify-center">
                       <div class="w-full px-4 flex justify-center">
                           <div class="relative">
                               <img alt="Profile Picture"
                               src="{% if user.profile.profile_picture %}{{ user.profile.profile_picture.url }}{% else %}https://static-00.iconduck.com/assets.00/profile-default-icon-2048x2045-u3j7s5nj.png{% endif %}"
                               class="shadow-xl rounded-full h-auto align-middle border-none absolute -m-16 -ml-20 lg:-ml-16 max-w-150-px">
                           </div>
                       </div>
                       <div class="w-full px-4 text-center mt-20">
                           <div class="text-center mt-12">
                               <h3 class="text-xl font-semibold leading-normal mb-2 text-blueGray-700 mb-2">
                                   {{ user.username }}
                               </h3>
                               <div class="text-sm leading-normal mt-0 mb-2 text-blueGray-400 font-bold uppercase">
                                   <i class="fas fa-envelope mr-2 text-lg text-blueGray-400"></i>
                                   {{ user.email }}
                               </div>
                               <div class="text-sm leading-normal mt-0 mb-2 text-blueGray-400 font-bold uppercase">
                                   <i class="fas fa-map-marker-alt mr-2 text-lg text-blueGray-400"></i>
                                   {{ user.profile.location }}
                               </div>
                               <div class="text-sm leading-normal mt-0 mb-2 text-blueGray-400 font-bold uppercase">
                                   <i class="fas fa-birthday-cake mr-2 text-lg text-blueGray-400"></i>
                                   {{ user.profile.birth_date }}
                               </div>
                           </div>
                       </div>
                   </div>
                   <div class="mt-10 py-10 border-t border-blueGray-200 text-center">
                        <button class="flex items-center rounded-md bg-gradient-to-tr 
                            from-slate-800 to-slate-700 py-2 px-4 border border-transparent text-center text-sm text-black transition-all shadow-sm hover:shadow-lg focus:bg-slate-700 focus:shadow-none active:bg-slate-700 hover:bg-slate-700 active:shadow-none disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none" type="button">
                            <a href="{% url 'image_upload' %}">
                                Upload Files

                            </a>

                        </button>
                       <div class="flex flex-wrap justify-center">
                           <div class="w-full lg:w-9/12 px-4">
                               <p class="mb-4 text-lg leading-relaxed text-blueGray-700">
                                   your clicks 
                               </p>
                            </div>
                        </div>
                        <section class="images_view">
                            <div class="container">
                                {% for image in images %}
                                    <figure class="{% if image.is_landscape %}landscape{% endif %}">
                                        <img src="{{ image.image.url }}" alt="{{ image.description }}">
                                        <figcaption><a href="#">{{ image.description }}</a></figcaption>
                                        <div class="flex flex-wrap justify-center">
                                            <button class="flex items-center rounded-md bg-gradient-to-tr from-slate-800 to-slate-700 py-2 px-4 border border-transparent text-center text-sm text-black transition-all shadow-sm hover:shadow-lg focus:bg-slate-700 focus:shadow-none active:bg-slate-700 hover:bg-slate-700 active:shadow-none disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none" type="button">
                                                <a href="{% url 'image_upload' %}">edit</a>
                                            </button>
                                            <button class="flex items-center rounded-md bg-gradient-to-tr from-slate-800 to-slate-700 py-2 px-4 border border-transparent text-center text-sm text-black transition-all shadow-sm hover:shadow-lg focus:bg-slate-700 focus:shadow-none active:bg-slate-700 hover:bg-slate-700 active:shadow-none disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none" type="button">
                                                <a href="{% url 'image_delete' image.pk %}">remove</a>
                                            </button>
                                        </div>
                                    </figure>
                                {% endfor %}
                            </div>
                        </section>
                        



                    </div>
                   

                   
               </div>
           </div>
       </div>
   </section>
   
   
   {% endblock  %}

myapp/templates/image_confirm_delete.html
{% extends "index.html" %}

{% block content %}
  <h2>Confirm Delete</h2>
  <p>Are you sure you want to delete "{{ object.description }}"?</p>
  <form method="post">
    {% csrf_token %}

    <button type="submit" class="flex items-center rounded-md bg-gradient-to-tr 
    from-slate-800 to-slate-700 py-2 px-4 border border-transparent text-center text-sm text-black transition-all shadow-sm hover:shadow-lg focus:bg-slate-700 focus:shadow-none active:bg-slate-700 hover:bg-slate-700 active:shadow-none disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none" 
    >Confirm Delete</button>
   
  
  </form>
  
  <a href="{% url 'image_list' %}">Cancel</a>

{% endblock %}

myapp/templates/image_form.html
{% extends "index.html" %}

{% block content %}
  <h2>Upload New Image</h2>
  <form method="post" enctype="multipart/form-data" style="max-width: 600px; margin: 0 auto; padding: 20px; background-color: #f9f9f9; border: 1px solid #ccc; border-radius: 10px;">
    {% csrf_token %}
    
      <p style="margin-bottom: 15px;">
          <label for="id_image" style="display: block; font-weight: bold; margin-bottom: 5px;">Image:</label>
          <input type="file" name="image" accept="image/*" required id="id_image" style="width: 100%; padding: 10px; border: 1px solid #ccc; border-radius: 5px;">
      </p>
  
      <p style="margin-bottom: 15px;">
          <label for="id_description" style="display: block; font-weight: bold; margin-bottom: 5px;">Description:</label>
          <textarea name="description" cols="40" rows="10" id="id_description" style="width: 100%; padding: 10px; border: 1px solid #ccc; border-radius: 5px;"></textarea>
      </p>
  
      <p style="margin-bottom: 15px;">
          <label for="id_tags" style="display: block; font-weight: bold; margin-bottom: 5px;">Tags:</label>
          <input type="text" name="tags" maxlength="255" id="id_tags" style="width: 100%; padding: 10px; border: 1px solid #ccc; border-radius: 5px;">
      </p>
  
  
      <button type="submit" style="padding: 10px 20px; background-color: #28a745; color: white; border: none; border-radius: 5px; cursor: pointer;">Upload</button>
    </form>
  <a href="{% url 'image_list' %}">Back to Gallery</a>
{% endblock %}

myapp/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://demos.creative-tim.com/notus-js/assets/styles/tailwind.css">
    <link rel="stylesheet" href="https://demos.creative-tim.com/notus-js/assets/vendor/@fortawesome/fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="{%  static 'mansorcss.css'%}">
    <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    


    <title>Pexels</title>
</head>
<body>
    {% comment %} nav bar  {% endcomment %}
<nav
class="flex items-center justify-between flex-wrap bg-white py-4 lg:px-12 shadow border-solid border-t-2 border-blue-700">
<div class="flex justify-between ">
    <div class="flex items-center flex-shrink-0 text-gray-800 mr-16">
        <span class="font-semibold  tracking-tight">Pexels</span>
    </div>
    <div class="block lg:hidden ">
        <button
            id="nav" 
            class="flex items-center px-3 py-2 border-2 rounded text-blue-700 border-blue-700 hover:text-blue-700 hover:border-blue-700">
            <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title>
                <path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/>
            </svg>
        </button>
    </div>
</div>

<div class="menu w-full lg:block flex-grow lg:flex lg:items-center lg:w-auto lg:px-3 px-8">
    <div class="text-md font-bold text-blue-700 lg:flex-grow">
        <a href="/"
           class="block mt-4 lg:inline-block lg:mt-0 hover:text-white px-4 py-2 rounded hover:bg-blue-700 mr-2">
            Home
        </a>
        {% if user.is_authenticated %}

        <a href="{% url "profile" %}"
           class=" block mt-4 lg:inline-block lg:mt-0 hov er:text-white px-4 py-2 rounded hover:bg-blue-700 mr-2">
            profile 
        </a>
        <a href="{% url "gallery" %}"
           class="block mt-4 lg:inline-block lg:mt-0 hover:text-white px-4 py-2 rounded hover:bg-blue-700 mr-2">
            Gallery
        </a>
        {% endif %}

        
    </div>
    <!-- This is an example component -->
    <div class="relative mx-auto text-gray-600 lg:block hidden">
      <form method="GET" action="{% url 'search' %}">
          <input
              class="border-2 border-gray-300 bg-white h-10 pl-2 pr-8 rounded-lg text-sm focus:outline-none"
              type="search" name="word" placeholder="Search" >
          
          <button type="submit" class="absolute right-0 top-0 mt-3 mr-2">
              <svg class="text-gray-600 h-4 w-4 fill-current" xmlns="http://www.w3.org/2000/svg"
                   version="1.1" id="Capa_1" x="0px" y="0px"
                   viewBox="0 0 56.966 56.966" style="enable-background:new 0 0 56.966 56.966;"
                   xml:space="preserve"
                   width="512px" height="512px">
                  <path
                      d="M55.146,51.887L41.588,37.786c3.486-4.144,5.396-9.358,5.396-14.786c0-12.682-10.318-23-23-23s-23,10.318-23,23  s10.318,23,23,23c4.761,0,9.298-1.436,13.177-4.162l13.661,14.208c0.571,0.593,1.339,0.92,2.162,0.92  c0.779,0,1.518-0.297,2.079-0.837C56.255,54.982,56.293,53.08,55.146,51.887z M23.984,6c9.374,0,17,7.626,17,17s-7.626,17-17,17  s-17-7.626-17-17S14.61,6,23.984,6z"/>
              </svg>
          </button>
      </form>
    </div>
  
    {% if user.is_authenticated %}
    
    <div class="flex">
        <form action="{% url 'logout' %}" method="post" class="inline">
            {% csrf_token %}
            <button type="submit" class="text-md px-4 py-2 rounded text-blue-700 ml-2 font-bold hover:text-white mt-4 hover:bg-blue-700 lg:mt-0">
                Logout
            </button>
        </form>
        {% if user.is_staff %}
        <a href="/superman"
           class=" block text-md px-4  ml-2 py-2 rounded text-blue-700 font-bold hover:text-white mt-4 hover:bg-blue-700 lg:mt-0">DB</a>

        {% endif %}

    </div>
    
    
    {% else %}
    <div class="flex ">
        <a href="{% url 'register' %}"
           class="block text-md px-4 py-2 rounded text-blue-700 ml-2 font-bold hover:text-white mt-4 hover:bg-blue-700 lg:mt-0">Sign
            in</a>

        <a href="{% url 'login_page' %}"
           class=" block text-md px-4  ml-2 py-2 rounded text-blue-700 font-bold hover:text-white mt-4 hover:bg-blue-700 lg:mt-0">login</a>
    </div>

    
    {% endif %}
    


</div>

</nav>
{% if user.is_staff %}
<div style="display:flex; justify-content:center; gap:10px">

    <div style="display: inline-block; padding: 10px; border: 2px solid black; font-size: 24px; font-weight: bold;">total number of  users: {{ usercount}}</div>
<br>
<div style="display: inline-block; padding: 10px; border: 2px solid black; font-size: 24px; font-weight: bold;">total no of  Photo uploded : {{imagecount}}</div>
</div>

<div style="display:flex; justify-content:center; gap:10px">
    <script>
        function loadUptime() {
            fetch("{% url 'get_uptime' %}")
            .then(response => response.json())
            .then(data => {
                document.getElementById("uptime-div").innerHTML = 
                    `Server Uptime: ${data.uptime_hours} hours, ${data.uptime_minutes} minutes, ${data.uptime_seconds} seconds`;
            })        

            .catch(error => console.error('Error fetching uptime:', error));
        }

        // Reload the div every 10 seconds
        setInterval(loadUptime, 10000); // 10000ms = 10 seconds

        // Initial load
        window.onload = loadUptime;
    </script>
    <p id="uptime-div">Loading uptime...</p>

</div>




{% endif %}


{% block content %}
  

<hr>

    <div class="content">

      <section class="images_view">
        <div class="container">
            {% for image in images %}
                <figure class="{% if image.is_landscape %}landscape{% endif %}">
                    <a href="{% url 'image_view' image.pk %}">
                        <img src="{{ image.image.url }}" alt="{{ image.description }}">
                    </a>
                </figure>
            {% endfor %}
        </div>
    </section>
    

            
            <!-- Add more images as grid-items -->
          </div>
    </section>
    </div>
    <!-- Page-specific content will go here -->
    {% endblock %}

<!-- Optional Footer -->
<footer  >

    {% comment %} <p>&copy; 2024 My Django Site</p> {% endcomment %}
</footer>
</body>
</html>
    
</body>
</html>

myapp/templates/profile.html
 {% extends "index.html" %}
 {% block content %}
    <section class="pt-16">
        <div class="w-full  px-6 mx-auto">
            <div class="relative flex flex-col min-w-0 break-words bg-white w-full mb-6 shadow-xl rounded-lg mt-16">
                <div class="px-6  ">
                    <div class="flex flex-wrap justify-center">
                        <div class="w-full px-4 flex justify-center">
                            <div class="relative">
                                <img alt="Profile Picture"
                                src="{% if user.profile.profile_picture %}{{ user.profile.profile_picture.url }}{% else %}https://static-00.iconduck.com/assets.00/profile-default-icon-2048x2045-u3j7s5nj.png{% endif %}"
                                class="shadow-xl rounded-full h-auto align-middle border-none absolute -m-16 -ml-20 lg:-ml-16 max-w-150-px">
                            </div>
                        </div>
                        <div class="w-full px-4 text-center mt-20">
                            <div class="text-center mt-12">
                                <h3 class="text-xl font-semibold leading-normal mb-2 text-blueGray-700 mb-2">
                                    {{ user.username }}
                                </h3>
                                <div class="text-sm leading-normal mt-0 mb-2 text-blueGray-400 font-bold uppercase">
                                    <i class="fas fa-envelope mr-2 text-lg text-blueGray-400"></i>
                                    {{ user.email }}
                                </div>
                                <div class="text-sm leading-normal mt-0 mb-2 text-blueGray-400 font-bold uppercase">
                                    <i class="fas fa-map-marker-alt mr-2 text-lg text-blueGray-400"></i>
                                    {{ user.profile.location }}
                                </div>
                                <div class="text-sm leading-normal mt-0 mb-2 text-blueGray-400 font-bold uppercase">
                                    <i class="fas fa-birthday-cake mr-2 text-lg text-blueGray-400"></i>
                                    {{ user.profile.birth_date }}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="mt-10 py-10 border-t border-blueGray-200 text-center">
                        <div class="flex flex-wrap justify-center">
                            <div class="w-full lg:w-9/12 px-4">
                                <p class="mb-4 text-lg leading-relaxed text-blueGray-700">
                                    {{ user.profile.bio }}
                                </p>
                            </div>
                        </div>

                    </div>
                    <label class="block text-gray-700 text-sm font-bold mb-2">
                        Update your profile here
                    </label>

                    <div class="flex flex-wrap justify-center mt-10">
                    

                        <form method="post" enctype="multipart/form-data" class="w-full lg:w-9/12 px-4">
                            {% csrf_token %}
                            <div class="mb-4">
                                <label class="block text-gray-700 text-sm font-bold mb-2" for="username">
                                    Username
                                </label>
                                <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="username" type="text" name="username" value="{{ user.username }}">
                            </div>

                            <div class="mb-4">
                                <label class="block text-gray-700 text-sm font-bold mb-2" for="email">
                                    Email
                                </label>
                                <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="email" type="email" name="email" value="{{ user.email }}">
                            </div>

                            <div class="mb-4">
                                <label class="block text-gray-700 text-sm font-bold mb-2" for="bio">
                                    Bio
                                </label>
                                <textarea class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="bio" name="bio">{{ user.profile.bio }}</textarea>
                            </div>

                            <div class="mb-4">
                                <label class="block text-gray-700 text-sm font-bold mb-2" for="location">
                                    Location
                                </label>
                                <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="location" type="text" name="location" value="{{ user.profile.location }}">
                            </div>

                            <div class="mb-4">
                                <label class="block text-gray-700 text-sm font-bold mb-2" for="birth_date">
                                    Birth Date
                                </label>
                                <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="birth_date" type="date" name="birth_date" value="{{ user.profile.birth_date }}">
                            </div>

                            <div class="mb-6">
                                <label class="block text-gray-700 text-sm font-bold mb-2" for="profile_picture">
                                    Profile Picture
                                </label>
                                <input class="block w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 cursor-pointer" id="profile_picture" name="profile_picture" type="file">
                            </div>

                            <div class="flex items-center justify-between  mb-4"> 
                                <button class="bg-blue-500 hover:bg-blue-700 text-semibold font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
                                    Update Profile
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    {% endblock  %}
 

myapp/templates/search.html
{% extends "index.html" %}

{% block content %}



<section class="images_view">
  <div class="container">
      {% for image in images %}
          <figure class="{% if image.is_landscape %}landscape{% endif %}">
              <a href="{% url 'image_view' image.pk %}">
                  <img src="{{ image.image.url }}" alt="{{ image.description }}">
              </a>
          </figure>
      {% endfor %}
  </div>
</section>

{% endblock %}